package com.example.ai.stock.service.notification;

public class GenerateHTML {

    public static String generateHTML(){
    return "<!DOCTYPE html>\n"
        + "    <html>\n"
        + "    <head>\n"
        + "    <style>\n"
        + "    thead,\n"
        + "tfoot {\n"
        + "    background-color: #3f87a6;\n"
        + "    color: #fff;\n"
        + "}\n"
        + "\n"
        + "tbody {\n"
        + "    background-color: #e4f0f5;\n"
        + "}\n"
        + "\n"
        + "caption {\n"
        + "    padding: 10px;\n"
        + "    caption-side: bottom;\n"
        + "}\n"
        + "\n"
        + "table {\n"
        + "    border-collapse: collapse;\n"
        + "    border: 2px solid rgb(200, 200, 200);\n"
        + "    letter-spacing: 1px;\n"
        + "    font-family: sans-serif;\n"
        + "    font-size: .8rem;\n"
        + "}\n"
        + "\n"
        + "td,\n"
        + "th {\n"
        + "    border: 1px solid rgb(190, 190, 190);\n"
        + "    padding: 5px 10px;\n"
        + "}\n"
        + "\n"
        + "td {\n"
        + "    text-align: center;\n"
        + "}\n"
        + "\n"
        + "    </style>\n"
        + "    </head>\n"
        + "    <body>\n"
        + "    <table>\n"
        + "    <caption>Pornhub Pages Summary</caption>\n"
        + "    <thead>\n"
        + "        <tr>\n"
        + "            <th>ID</th>\n"
        + "            <th scope=\"col\">Progress</th>\n"
        + "            <th scope=\"col\">Stucked</th>\n"
        + "            <th scope=\"col\">Finished</th>\n"
        + "            <th scope=\"col\">Busy</th>\n"
        + "        </tr>\n"
        + "    </thead>\n"
        + "    <tbody>\n"
        + "        ${rows}\n"
        + "    </tbody>\n"
        + "</table>\n"
        + "    </body>\n"
        + "    </html>";
    }
}
